name: test 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: build docker image
      run: cd src && docker build -t stft . && cd ..

    - name: run tests 
      run: cd src && docker run --rm stft bash -c "cd /project && make test" && cd ..

