name: test 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: cd src && docker build -t stft . && cd ..

    - name: Run tests 
      run: docker run --rm -v $(pwd):/project stft bash -c "cd /project/src && make test"

